spring.application.name: service--pedido

server.port: ${SERVER_PORT:5002}

logging.level:
  org.zalando.logbook: TRACE
  org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management:
  metrics.tags.application: ${spring.application.name}
  endpoints:
    web:
      exposure.include: "*"
      export.prometheus.enabled: true
  endpoint:
    health.show-components: ALWAYS
    metrics.enabled: true
    prometheus.enabled: true

opentracing.jaeger:
  udp-sender:
    host: ${JAEGER_HOST:localhost}
    port: ${JAEGER_PORT:6831}
  log-spans: false
  enable-b3-propagation: true

spring.data.mongodb:
  host: ${MONGODB_HOST:localhost}
  port: ${MONGODB_PORT:27017}
  database: ${MONGODB_DATABASE:db_pedido}
  username: ${MONGODB_USERNAME:admin}
  password: ${MONGODB_PASSWORD:admin}
  authentication-database: ${MONGODB_AUTH_DATABASE:admin}